version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: my_redis
    restart: always
    ports:
      - "6677:6677"
    volumes:
      - redis_data:/data
    command: redis-server --port 6677 --appendonly yes

volumes:
  redis_data:
    driver: local
