mybatis:
  type-aliases-package: com.yelm.jwtlogin.user.entity,com.yelm.jwtlogin.user.vo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: "NULL"

spring:
  application:
    name: "jwtlogin"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/jwtlogin?currentSchema=public
    username: user
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  # Redis config
  data:
    redis:
      host: localhost
      port: 6677

  # JWT Secret Key & Expire time
  jwt:
    secret: jwtloginExampleqpeorijdkfkdafjaldkfjadkfjadkjfeqradkfjadkfjapt
    # Refresh Expires in 24hr
    refreshexpirems : 86400000
    # Access Expires in 30 min
    accessexprirems : 1800000

server:
  port: 8080


# Spring Security Logging Option
logging:
  level:
    org:
      springframework:
        security: TRACE
    root: debug
    sun.rmi.loader: WARN
    sun.rmi.transport.tcp: warn
    javax.management.remote.rmi: WARN

# CORS 주소 (FE 주소)
cors:
  allowed-origins: "http://localhost:8888"